2022-03-30 19:34:18,901 (root) Initializing Heralding version 1.0.7
2022-03-30 19:34:19,114 (heralding.honeypot) Using default wordlist file: "/usr/lib/python3.9/site-packages/heralding/wordlist.txt", if you want to customize values please copy this file to the current working directory
2022-03-30 19:34:19,149 (heralding.reporting.file_logger) File logger: Using /var/log/heralding/auth.csv to log authentication attempts in CSV format.
2022-03-30 19:34:19,149 (heralding.reporting.file_logger) File logger: Using /var/log/heralding/session.csv to log unified session data in CSV format.
2022-03-30 19:34:19,149 (heralding.reporting.file_logger) File logger: Using /var/log/heralding/log_session.json to log complete session data in JSON format.
2022-03-30 19:34:23,495 (heralding.honeypot) Found public ip: 34.121.180.85
2022-03-30 19:34:23,496 (heralding.honeypot) Started RDP capability listening on port 3389
2022-03-30 19:34:23,496 (heralding.honeypot) Started Telnet capability listening on port 23
2022-03-30 19:34:23,497 (heralding.honeypot) Started Pop3 capability listening on port 110
2022-03-30 19:34:25,482 (heralding.honeypot) Started Pop3S capability listening on port 995
2022-03-30 19:34:25,483 (heralding.honeypot) Started Http capability listening on port 80
2022-03-30 19:34:25,483 (heralding.honeypot) Started Imap capability listening on port 143
2022-03-30 19:34:25,484 (heralding.honeypot) Started MySQL capability listening on port 3306
2022-03-30 19:34:25,485 (heralding.honeypot) Started Vnc capability listening on port 5900
2022-03-30 19:34:25,485 (heralding.honeypot) Started PostgreSQL capability listening on port 5432
2022-03-30 19:34:25,486 (heralding.honeypot) Started smtp capability listening on port 25
2022-03-30 19:34:27,000 (heralding.honeypot) Started https capability listening on port 443
2022-03-30 19:34:27,000 (heralding.honeypot) Started Socks5 capability listening on port 1080
2022-03-30 19:34:28,178 (heralding.honeypot) Started Imaps capability listening on port 993
2022-03-30 19:34:28,740 (heralding.honeypot) Started SSH capability listening on port 22
2022-03-30 19:34:35,379 (heralding.honeypot) Started smtps capability listening on port 465
2022-03-30 19:34:35,380 (heralding.honeypot) Started ftp capability listening on port 21
2022-03-30 20:34:23,775 (heralding.honeypot) Found public ip: 34.121.180.85
2022-03-30 22:44:47,343 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5526997520>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-31 00:18:18,575 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5526864340>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-31 01:38:52,386 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5526864190>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-31 03:38:02,313 (heralding.honeypot) Found public ip: 34.121.180.85
2022-03-31 04:42:08,113 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f55268644c0>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-31 04:42:08,122 (asyncio) Task exception was never retrieved
future: <Task finished name='Task-221' coro=<HandlerBase.handle_session() done, defined at /usr/lib/python3.9/site-packages/heralding/capabilities/handlerbase.py:74> exception=KeyError('user')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/heralding/capabilities/handlerbase.py", line 86, in handle_session
    await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/usr/lib/python3.9/site-packages/heralding/capabilities/postgresql.py", line 13, in execute_capability
    await self._handle_session(session, reader, writer)
  File "/usr/lib/python3.9/site-packages/heralding/capabilities/postgresql.py", line 38, in _handle_session
    username = login_dict['user']
KeyError: 'user'
2022-03-31 05:52:51,085 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5526864c40>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-31 07:56:46,265 (heralding.honeypot) Found public ip: 34.121.180.85
2022-03-31 10:14:41,710 (heralding.honeypot) Found public ip: 34.121.180.85
2022-03-31 11:31:01,768 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f552686c040>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-31 13:01:34,441 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f552685cf40>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-31 14:19:41,242 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f552685caf0>: Failed to establish a new connection: [Errno -3] Try again'))
