2022-04-04 16:07:55,985 (root) Initializing Heralding version 1.0.7
2022-04-04 16:07:56,277 (heralding.honeypot) Using default wordlist file: "/usr/lib/python3.9/site-packages/heralding/wordlist.txt", if you want to customize values please copy this file to the current working directory
2022-04-04 16:07:56,283 (heralding.reporting.file_logger) File logger: Using /var/log/heralding/auth.csv to log authentication attempts in CSV format.
2022-04-04 16:07:56,283 (heralding.reporting.file_logger) File logger: Using /var/log/heralding/session.csv to log unified session data in CSV format.
2022-04-04 16:07:56,287 (heralding.reporting.file_logger) File logger: Using /var/log/heralding/log_session.json to log complete session data in JSON format.
2022-04-04 16:07:59,562 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-04 16:07:59,563 (heralding.honeypot) Started RDP capability listening on port 3389
2022-04-04 16:07:59,563 (heralding.honeypot) Started Telnet capability listening on port 23
2022-04-04 16:07:59,564 (heralding.honeypot) Started Pop3 capability listening on port 110
2022-04-04 16:08:01,288 (heralding.honeypot) Started Pop3S capability listening on port 995
2022-04-04 16:08:01,288 (heralding.honeypot) Started Http capability listening on port 80
2022-04-04 16:08:01,289 (heralding.honeypot) Started Imap capability listening on port 143
2022-04-04 16:08:01,290 (heralding.honeypot) Started MySQL capability listening on port 3306
2022-04-04 16:08:01,291 (heralding.honeypot) Started Vnc capability listening on port 5900
2022-04-04 16:08:01,291 (heralding.honeypot) Started PostgreSQL capability listening on port 5432
2022-04-04 16:08:01,292 (heralding.honeypot) Started smtp capability listening on port 25
2022-04-04 16:08:04,791 (heralding.honeypot) Started https capability listening on port 443
2022-04-04 16:08:04,792 (heralding.honeypot) Started Socks5 capability listening on port 1080
2022-04-04 16:08:06,485 (heralding.honeypot) Started Imaps capability listening on port 993
2022-04-04 16:08:07,903 (heralding.honeypot) Started SSH capability listening on port 22
2022-04-04 16:08:15,953 (heralding.honeypot) Started smtps capability listening on port 465
2022-04-04 16:08:15,953 (heralding.honeypot) Started ftp capability listening on port 21
2022-04-04 17:52:14,631 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b59eca670>: Failed to establish a new connection: [Errno -3] Try again'))
2022-04-04 20:20:34,593 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-04 20:20:34,830 (asyncio) Task exception was never retrieved
future: <Task finished name='Task-110' coro=<HandlerBase.handle_session() done, defined at /usr/lib/python3.9/site-packages/heralding/capabilities/handlerbase.py:74> exception=KeyError('user')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/heralding/capabilities/handlerbase.py", line 86, in handle_session
    await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/usr/lib/python3.9/site-packages/heralding/capabilities/postgresql.py", line 13, in execute_capability
    await self._handle_session(session, reader, writer)
  File "/usr/lib/python3.9/site-packages/heralding/capabilities/postgresql.py", line 38, in _handle_session
    username = login_dict['user']
KeyError: 'user'
2022-04-04 21:21:26,383 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b59e65bb0>: Failed to establish a new connection: [Errno -3] Try again'))
2022-04-04 22:40:45,290 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b59e45ac0>: Failed to establish a new connection: [Errno -3] Try again'))
2022-04-05 01:21:23,980 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b59e6f580>: Failed to establish a new connection: [Errno -3] Try again'))
2022-04-05 04:31:11,977 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-05 06:29:30,112 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b59e6fd00>: Failed to establish a new connection: [Errno -3] Try again'))
