[30042022 16:58:59] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[30042022 16:58:59] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[30042022 16:59:01] log /root/dionaea/src/signals.c:36-warning: sigterm_cb loop 0x7f411eab7720 w 0x55cf81110230 revents 1024
[30042022 16:59:21] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[30042022 16:59:21] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[30042022 17:00:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:01:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:02:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:02:52] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:127-warning: p.haslayer(Raw): b'\x00\x00'
[30042022 17:02:52] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:157-warning: p.haslayer(Raw): b'\x00\x00'
[30042022 17:03:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:04:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:05:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:06:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:07:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:08:20] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[30042022 17:08:20] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[30042022 17:08:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:08:51] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[30042022 17:09:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:10:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:11:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:11:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:11:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:12:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:12:37] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:12:37] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:13:14] tftp /opt/dionaea/lib/dionaea/python/dionaea/tftp.py:719-warning: Requested file /opt/dionaea/var/dionaea/roots/tftp/a.pdf does not exist.
[30042022 17:13:14] tftp /opt/dionaea/lib/dionaea/python/dionaea/tftp.py:723-warning: Requested file not found: /opt/dionaea/var/dionaea/roots/tftp/a.pdf
[30042022 17:13:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:13:56] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:13:56] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:14:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:15:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:16:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:17:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:18:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:19:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:20:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:21:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:22:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:23:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:24:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:25:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:26:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:27:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:28:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:29:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:29:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:29:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:30:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:31:04] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:31:04] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:31:04] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:13] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:13] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
